--- 
- 
  become: true
  hosts: all
  name: "First playbook nginx installation"
  tasks: 
    - 
      name: "install nginx"
      yum: 
        name: nginx
        state: latest
    - 
      name: "status nginx"
      service: 
        name: nginx
        start: started
